"""add phone_number

Revision ID: 235555e1bdd6
Revises: 642bd227f624
Create Date: 2026-04-10 12:07:09.600306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '235555e1bdd6'
down_revision: Union[str, Sequence[str], None] = '642bd227f624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
