"""adding amount to db

Revision ID: 54483abb8d9a
Revises: 746de644d7b4
Create Date: 2026-03-05 20:02:22.204152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54483abb8d9a'
down_revision: Union[str, Sequence[str], None] = '746de644d7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    import sqlalchemy as sa
from alembic import op

def upgrade():
    # 1) add amount safely (existing rows get 0)
    op.add_column(
        "users",
        sa.Column("amount", sa.Float(), nullable=False, server_default=sa.text("0"))
    )

    # 2) FIX existing rows that have username = NULL
    op.execute("UPDATE users SET username = CONCAT('user_', id) WHERE username IS NULL;")

    # 3) now it's safe to enforce NOT NULL
    op.alter_column(
        "users", "username",
        existing_type=sa.VARCHAR(length=450),
        nullable=False
    )

    # 4) optional: remove server default after migration
    op.alter_column("users", "amount", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=450),
               nullable=True)
    op.drop_column('users', 'amount')
    # ### end Alembic commands ###
