"""add first_name and last_name 3al users

Revision ID: 642bd227f624
Revises: df712b90cd1c
Create Date: 2026-04-09 08:47:48.191732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '642bd227f624'
down_revision: Union[str, Sequence[str], None] = 'df712b90cd1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('first_name', sa.String(length=450), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=450), nullable=True))

    op.execute("""
        UPDATE users
        SET first_name = 'Unknown',
            last_name = 'Unknown'
        WHERE first_name IS NULL OR last_name IS NULL
    """)

    op.alter_column('users', 'first_name', nullable=False)
    op.alter_column('users', 'last_name', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
