"""add recyclables table

Revision ID: 760791679b0b
Revises: ad1a76efb0b0
Create Date: 2026-03-04 14:02:50.320056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760791679b0b'
down_revision: Union[str, Sequence[str], None] = 'ad1a76efb0b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recyclables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organic', sa.Float(), nullable=True),
    sa.Column('paper', sa.Float(), nullable=True),
    sa.Column('plastic', sa.Float(), nullable=True),
    sa.Column('glass', sa.Float(), nullable=True),
    sa.Column('metal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recyclables')
    # ### end Alembic commands ###
