"""add user total recycled

Revision ID: 87f3ddaed929
Revises: 9545f1b2a676
Create Date: 2026-03-20 22:52:52.263106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f3ddaed929'
down_revision: Union[str, Sequence[str], None] = '9545f1b2a676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_total_recycled',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_organic', sa.Float(), nullable=True),
    sa.Column('total_paper', sa.Float(), nullable=True),
    sa.Column('total_plastic', sa.Float(), nullable=True),
    sa.Column('total_glass', sa.Float(), nullable=True),
    sa.Column('total_metal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('recyclables')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recyclables',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organic', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('paper', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('plastic', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('glass', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('recyclables_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recyclables_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('recyclables_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('user_total_recycled')
    # ### end Alembic commands ###
