"""company table 

Revision ID: a7ad07793fbc
Revises: e5115d6639f1
Create Date: 2026-03-03 21:08:24.681819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ad07793fbc'
down_revision: Union[str, Sequence[str], None] = 'e5115d6639f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('company_name', sa.String(length=450), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'company_name')
    # ### end Alembic commands ###
