"""added recy id to requests 

Revision ID: d3520640ccf0
Revises: 2ee4129f9fc4
Create Date: 2026-05-23 11:21:24.685713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3520640ccf0'
down_revision: Union[str, Sequence[str], None] = '2ee4129f9fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('recyclable_item_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_requests_recyclable_item_id'), 'requests', ['recyclable_item_id'], unique=False)
    op.create_foreign_key(None, 'requests', 'recyclable_items', ['recyclable_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_index(op.f('ix_requests_recyclable_item_id'), table_name='requests')
    op.drop_column('requests', 'recyclable_item_id')
    # ### end Alembic commands ###
