"""zeded el date taba3 el pickup 

Revision ID: fe27c48e55e2
Revises: a2c62a8e2e96
Create Date: 2026-04-14 20:01:56.459641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe27c48e55e2'
down_revision: Union[str, Sequence[str], None] = 'a2c62a8e2e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recyclable_items', sa.Column('scheduled_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recyclable_items', 'scheduled_date')
    # ### end Alembic commands ###
